[package]
name = "advent2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "adventlib"
path = "src/lib.rs"

[[bin]]
name = "advent2019"
path = "src/main.rs"


[dependencies]
clap = "2"
